project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4000

website:
  title: "Jacob Morrison"
  description: "Personal Website"
  page-footer:
    left: "Copyright 2024, Jacob Morrison"
    right:
      - icon: github
        href: https://github.com/jamorrison
  sidebar:
    style: "docked"
    background: "#E3E3E3"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About Me
      - href: publications.qmd
        text: Publications

format:
  html:
    theme: flatly
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"
    number-sections: false



