---
title: Publications
---

# Biology

## 2024
- Zhou, W., Johnson, B.K., Morrison, J. *et al*.
  BISCUIT: an efficient, standards-compliant tool suite for simultaneous genetic and epigenetic inference in bulk and single-cell studies.
  *Nucleic Acids Research*. 52, 6 (2024). <https://doi.org/10.1093/nar/gkae097>

## 2023
- Morrison, J. *et al*.
  Dupsifter: a lightweight duplicate marking tool for whole genome bisulfite sequencing.
  *Bioinformatics*. 39, 12 (2023). <https://doi.org/10.1093/bioinformatics/btad729>

## 2021
- Morrison, J., *et al*.
  Evaluation of whole-genome DNA methylation sequencing library preparation protocols.
  *Epigenetics \& Chromatin*. 14, 28 (2021). <https://doi.org/10.1186/s13072-021-00401-y>

# Dissertation
- Morrison, J.
  Effect Of New Samples In The T2K Off-Axis Near Detector For The T2K Oscillation Analysis.
  *Ph.D. dissertation*, Michigan State University. (2019). <https://t2k.org/docs/thesis/104/>

# Physics

## 2021 
- The T2K Collaboration. Abe, K, *et al*.
  Measurements of $\overline{\nu}_{\mu}$ and $\overline{\nu}_{\mu} + \nu_{\mu}$ charged-current cross-sections without detected pions or protons on water and hydrocarbon at a mean anti-neutrino energy of 0.86 GeV.
  *Prog. Theor. Exp. Phys*. 2021, 4 (2021). <https://doi.org/10.1093/ptep/ptab014>

## 2020
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of the charged-current electron (anti-)neutrino inclusive cross-sections at the T2K off-axis near detector ND280.
  *J. High Energ. Phys*. 2020, 114 (2020). <https://doi.org/10.1007/JHEP10(2020)114>
- The T2K Collaboration. Abe, K., *et al*.
  First measurement of the charged current $\bar{\nu}_{\mu}$ double differential cross section on a water target without pions in the final state.
  *Phys. Rev. D*. 102, 012007 (2020). <https://doi.org/10.1103/PhysRevD.102.012007>
- The T2K Collaboration. Abe, K., *et al*.
  First combined measurement of the muon neutrino and antineutrino charged-current cross section without pions in the final state at T2K.
  *Phys. Rev. D*. 101, 112001 (2020). <https://doi.org/10.1103/PhysRevD.101.112001>
- The T2K Collaboration. Abe, K., *et al*.
  Constraint on the matter–antimatter symmetry-violating phase in neutrino oscillations.
  *Nature*. 580, 339--344 (2020). <https://doi.org/10.1038/s41586-020-2177-0>
- The T2K Collaboration. Abe, K., *et al*.
  Search for Electron Antineutrino Appearance in a Long-Baseline Muon Antineutrino Beam.
  *Phys. Rev. Lett*. 124, 161802 (2020). <https://doi.org/10.1103/PhysRevLett.124.161802>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of the muon neutrino charged-current single $\pi^+$ production on hydrocarbon using the T2K off-axis near detector ND280.
  *Phys. Rev. D*. 101, 012007 (2020). <https://doi.org/10.1103/PhysRevD.101.012007>

## 2019
- The T2K Collaboration. Abe, K., *et al*.
  Search for heavy neutrinos with the T2K near detector ND280.
  *Phys. Rev. D*. 100, 052006 (2019). <https://doi.org/10.1103/PhysRevD.100.052006>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of neutrino and antineutrino neutral-current quasielasticlike interactions on oxygen by detecting nuclear deexcitation $\gamma$ rays.
  *Phys. Rev. D*. 100, 112009 (2019). <https://doi.org/10.1103/PhysRevD.100.112009>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of the muon neutrino charged-current cross sections on water, hydrocarbon and iron, and their ratios, with the T2K on-axis detectors.
  *Prog. Theor. Exp. Phys*. 9, 093C02 (2019). <https://doi.org/10.1093/ptep/ptz070>
- The T2K Collaboration. Abe, K., *et al*.
  Search for neutral-current induced single photon production at the ND280 near detector in T2K.
  *J. Phys. G: Nucl. Part. Phys*. 46, 08LT01 (2019). <https://doi.org/10.1088/1361-6471/ab227d>
- The T2K Collaboration. Abe, K., *et al*.
  Search for light sterile neutrinos with the T2K far detector Super-Kamiokande at a baseline of 295 km.
  *Phys. Rev. D*. 99, 071103(R) (2019). <https://doi.org/10.1103/PhysRevD.99.071103>

## 2018
- The T2K Collaboration. Abe, K., *et al*.
  Characterization of nuclear effects in muon-neutrino scattering on hydrocarbon with a measurement of final-state kinematics and correlations in charged-current pionless interactions at T2K.
  *Phys. Rev. D*. 98, 032003 (2018). <https://doi.org/10.1103/PhysRevD.98.032003>
- The T2K Collaboration. Abe, K., *et al*.
  Search for $CP$ Violation in Neutrino and Antineutrino Oscillations by the T2K Experiment with $2.2\times{10}^{21}$ Protons on Target.
  *Phys. Rev. Lett*. 121, 171802 (2018). <https://doi.org/10.1103/PhysRevLett.121.171802>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of inclusive double-differential $\nu_\mu$ charged-current cross section with improved acceptance in the T2K off-axis near detector.
  *Phys. Rev. D*. 98, 012004 (2018). <https://doi.org/10.1103/PhysRevD.98.012004>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of the single $\pi^0$ production rate in neutral current neutrino interactions on water.
  *Phys. Rev. D*. 97, 032002 (2018). <https://doi.org/10.1103/PhysRevD.97.032002>
- The T2K Collaboration. Abe, K., *et al*.
  First measurement of the $\nu_{\mu}$ charged-current cross section on a water target without pions in the final state.
  *Phys. Rev. D*. 97, 012001 (2018). <https://doi.org/10.1103/PhysRevD.97.012001>

## 2017
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of neutrino and antineutrino oscillations by the T2K experiment including a new additional sample of $\nu_e$ interactions at the far detector.
  *Phys. Rev. D*. 96, 092006 (2017). <https://doi.org/10.1103/PhysRevD.96.092006>
- The T2K Collaboration. Abe, K., *et al*.
  Measurement of $\bar{\nu}_{\mu}$ and $\nu_{\mu}$ charged current inclusive cross sections and their ratio with the T2K off-axis near detector.
  *Phys. Rev. D*. 96, 052001 (2017). <https://doi.org/10.1103/PhysRevD.96.092006>
- The T2K Collaboration. Abe, K., *et al*.
  Updated T2K measurements of muon neutrino and antineutrino disappearance using 1.5 $\times 10^{21}$ protons on target.
  *Phys. Rev. D*. 96, 011102(R) (2017). <https://doi.org/10.1103/PhysRevD.96.011102>
- The T2K Collaboration. Abe, K., *et al*.
  Search for Lorentz and CPT violation using sidereal time dependence of neutrino flavor transitions over a short baseline.
  *Phys. Rev. D*. 95, 111101(R) (2017). <https://doi.org/10.1103/PhysRevD.96.011102>

## 2015
- GENIE Collaboration. Alam, M., *et al*.
  GENIE Production Release 2.10.0.
  (2015). Preprint at <https://arxiv.org/abs/1512.06882v2>
